accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # url(r"login/$", views.LoginView.as_view(), name="login"),
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'edit/$', views.Edit, name='edit'),
    url(r'^login/$', views.login, name='login'),
    url(r'^profile/$', views.Profile, name='profile'),
]

g2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r"^accounts/", include("accounts.urls", namespace='accounts')),
    url(r"^prof/", include("prof.urls", namespace='prof')),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^sellers/', include('sellers.urls', namespace='sellers')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'home/$', views.Home, name='home'),
    url(r'^checkouts/(?P<pk>\d+)/', views.new_checkout, name='new_checkout'),
    url(r'new/$', views.New, name='new'),
    url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.Edit, name='edit'),
    url(r'my/$', views.MyListings, name='my_listings'),
    url(r'^client_token', views.client_token, name='client_token'),
    url(r'^checkouts/create/(?P<pk>\d+)', views.create_checkout, name='create_checkout'),
    url(r'^checkouts/(?P<transaction_id>\w+)/(?P<pk>\d+)', views.show_checkout, name='show_checkout'),
]

sellers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'home/$', views.Home, name='home'),
    url(r'new/$', views.New, name='new'),
    url(r'new2/$', views.TwoNew, name='two_new'),
    url(r'^profile/$', views.Profile, name='profile'),
    url(r'redeem/(?P<pk>\d+)/$', views.redeem, name='redeem'),

]

sellers/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from django.core.validators import RegexValidator


# Create your models here.
# Create the form class.
class Seller(models.Model):
    first_name = models.CharField(max_length=50)
    last_name = models.CharField(max_length=50)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, blank=True, null=True)
    avatar = models.FileField(upload_to='avatar/', null=True)
    created = models.DateTimeField(default=timezone.now)
    street = models.CharField(max_length=100)
    city = models.CharField(max_length=100)
    state = models.CharField(max_length=100)
    zipp = models.CharField(max_length=5, validators=[RegexValidator(r'^\d{1,10}$')])
    display_name = models.CharField(max_length=50, unique=True)
    merch = models.CharField(max_length=50, default='')
    email = models.EmailField(default='')
    

    
    
    UNITED_STATES = 'us'
    CANADA = 'ca'

    COUNTRY_CHOICES = (
        (UNITED_STATES, 'United State'),
        (CANADA, 'Canada',)
    )

    country = models.CharField(
        max_length = 2,
        choices = COUNTRY_CHOICES,
        default = UNITED_STATES,
    )

    def __str__(self):              # __unicode__ on Python 2
        return self.display_name

sellers/forms.py
from django import forms
from . import models
from django.apps import apps
from django.contrib.auth import get_user_model
from prof.models import Code
from sellers.models import Seller

class SellerForm(forms.ModelForm):
    class Meta:
        model = models.Seller
        fields = [
            'first_name',
            'last_name',
             'avatar',
             'street',
             'city',
             'state',
             'zipp',
             'display_name',
             'email',
        ] 


    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["avatar"].widget.attrs.update({'class': 'form-control'})
        self.fields["first_name"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'First Name'})
        self.fields["last_name"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Last Name'})
        self.fields["street"].widget.attrs.update({'class': 'form-control','placeholder': 'Street'})
        self.fields["city"].widget.attrs.update({'class': 'form-control', 'placeholder': 'City'})
        self.fields["state"].widget.attrs.update({'class': 'form-control', 'placeholder': 'State'})
        self.fields["zipp"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Zip'})
        self.fields["display_name"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Display Name'})
        self.fields["email"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Email'})
        
        

class PartialUserForm(forms.ModelForm):
    class Meta:
        model = get_user_model()
        fields = [

        ]


class CodeForm(forms.ModelForm):
    class Meta:
        model = Code
        fields = {
            
        }

class MerchForm(forms.Form):
    email = forms.EmailField(label='Email', max_length=100)
    phone = forms.CharField(max_length=10)
    dob = forms.CharField(max_length=10)
    ssn = forms.CharField(max_length=10)
    legal = forms.CharField(max_length=100)
    dba = forms.CharField(max_length=100)
    tax = forms.CharField(max_length=100)
    biz_street = forms.CharField(max_length=100)
    biz_state = forms.CharField(max_length=100)
    biz_city = forms.CharField(max_length=100)
    biz_zipp = forms.CharField(max_length=100)
    funding_name = forms.CharField(max_length=100)
    acc_num = forms.CharField(max_length=100)
    routing = forms.CharField(max_length=100)
    tos = forms.BooleanField()




    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["email"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'First Name'})
        self.fields["phone"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Phone'})
        self.fields["dob"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'DOB'})
        self.fields["ssn"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'SSN'})
        self.fields["legal"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Legal Name'})
        self.fields["dba"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'DBA'})
        self.fields["tax"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Tax Id'})
        self.fields["biz_street"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'street'})
        self.fields["biz_city"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'city'})
        self.fields["biz_state"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'state'})
        self.fields["biz_zipp"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'biz_zipp'})
        self.fields["funding_name"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Bank Account Name'})
        self.fields["acc_num"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Account Number'})
        self.fields["routing"].widget.attrs.update({'class': 'form-control field', 'placeholder': 'Routing Number'})
        self.fields["tos"].widget.attrs.update({'class': 'form-control field'})


class AddMerchForm(forms.ModelForm):
    class Meta:
        model = Seller
        fields = [
            'merch'
        ]

sellers/views.py
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from . import forms
from . import models
from listings.models import Listing
from accounts.models import User
from django.contrib.auth.decorators import login_required
from accounts.forms import UserCreateForm
from accounts.models import User
from listings.models import Bought
from sellers.models import Seller
from django.shortcuts import get_object_or_404, render
import random
import string
import datetime
import braintree


# Create your views here.
@login_required
def Home(request):
    user = request.user
    listings = Listing.objects.filter(user_id=request.user.id)
    return render(request, 'sellers/home.html', {'listings':listings}) 

@login_required
def New(request):
    form = forms.SellerForm()
    signup = forms.PartialUserForm(instance=request.user)
    # if this is a POST request we need to process the form data
    # create a form instance and populate it with data from the request)
    # check whether it's valid:
    if request.method == 'POST':
        form = forms.SellerForm(request.POST, request.FILES)
        signup = forms.PartialUserForm(instance=request.user, data=request.POST, files=request.FILES)
        if form.is_valid():
            seller = form.save(commit=False)
            seller.user = request.user
            seller.save()
            sp = signup.save(commit=False)
            sp.is_seller = True
            sp.save()
            return HttpResponseRedirect('/sellers/new2/')
        else:
            messages.add_message(request, messages.ERROR, "Error")
            print(form.errors)
            return HttpResponseRedirect('/sellers/new/')
    return render(request, 'sellers/new.html', {'form': form, 'signup':signup})

    

def TwoNew(request):
    seller = get_object_or_404(Seller, user=request.user)
    merch = forms.MerchForm()
    if request.method == 'POST':
        merch = forms.MerchForm(request.POST)
        terms = request.POST.get('tos')
        if terms == 'on':
            terms = True
        else:
            terms = False

        merchant_account_params = {
            'individual': {
                'first_name': seller.first_name,
                'last_name': seller.last_name,
                'email': seller.email,
                'phone': request.POST.get('phone'),
                'date_of_birth': request.POST.get('dob'),
                'ssn': request.POST.get('ssn'),
                'address': {
                    'street_address': seller.street,
                    'locality': seller.city,
                    'region': seller.state,
                    'postal_code': seller.zipp
                }
            },
            'business': {
                'legal_name': request.POST.get('legal'),
                'dba_name': request.POST.get('dba'),
                'tax_id': request.POST.get('tax'),
                'address': {
                    'street_address': request.POST.get('biz_street'),
                    'locality': request.POST.get('biz_city'),
                    'region': request.POST.get('biz_state'),
                    'postal_code': request.POST.get('biz_zipp')
                }
            },
            'funding': {
                'descriptor': request.POST.get('funding_name'),
                'destination': braintree.MerchantAccount.FundingDestination.Bank,
                'email': seller.email,
                'mobile_phone': request.POST.get('phone'),
                'account_number': request.POST.get('acc_num'),
                'routing_number': request.POST.get('routing'),
            },
            "tos_accepted": terms,
            "master_merchant_account_id": "BCSW"
        }




        result = braintree.MerchantAccount.create(merchant_account_params)
        form = forms.AddMerchForm(instance=seller)
        up = form.save(commit=False)
        up.merch = result.merchant_account.id
        up.save()
        return HttpResponseRedirect('/sellers/home/')
    return render(request, 'sellers/new2.html', {'merch':merch})

@login_required
def Profile(request):
    uid = request.user.id
    boughts = Bought.objects.filter(seller_id=uid)

    return render(request, 'sellers/profile.html', {'boughts': boughts})


def redeem(request, pk):
    
    bought = get_object_or_404(Bought, pk=pk)
    code = ''.join(random.SystemRandom().choice(string.ascii_uppercase + string.digits + string.ascii_lowercase) for _ in range(6))
    now = datetime.datetime.now()
    expire = now + datetime.timedelta(minutes = 10)

    form = forms.CodeForm()
    form = forms.CodeForm(request.POST)
    bought = get_object_or_404(Bought, pk=pk)
    c = form.save(commit=False)
    c.bought = Bought.objects.get(id = bought.id)
    c.code = code
    c.expire = expire
    c.save()

    return render(request, 'sellers/redeem.html', {'form':form, 'bought': bought, 'code': code})

sellers/templates/sellers/home.html
{% extends "layout.html" %}
{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-primary"{% endif %}>{{ message }}</li>
    {% endfor %}
</ul>
{% endif %}
<h1>Sellers Home</h1>
<div>
    {% if listings %}
    {%  for listing in listings %}
        {% if forloop.first %}<div class="row">{% endif %}
            <div class="col-sm-4">
                <div class="card" style="width: 20rem;">
                    <img class="card-img-top" src="{{ MEDIA_URL }}/{{listing.document}}" alt="Card image cap">
                    <div class="card-body">
                    <h4 class="card-title">{{ listing.listing_name }}</h4>
                    <p class="card-text">{{listing.desc}}</p>
                    <a href="{% url 'listings:detail' pk=listing.pk %}" class="btn btn-primary">Go somewhere</a>
                    <a href="{% url 'listings:edit' pk=listing.pk %}" class="btn btn-danger">Edit</a>
                    </div>
                </div>
            </div>
            {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
            {% if forloop.last %}</div>{% endif %}
    {% endfor %}
    {% else %}
        <h1>You have no listings</h1>
    {% endif %}
    
</div>
{% endblock %}

sellers/templates/sellers/new.html
{% extends "layout.html" %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-danger alert-dismissible fade show" role="alert"{% endif %}>{{ message }}>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
    </li>
    
    {% endfor %}
</ul>
{% endif %}



<div class="form-container col-6 offset-3">
    <div class="row">
        <h1>Become a Provider</h1>
    </div>
    <div class="row">
        <div class="form">
            <form  method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form.non_field_errors }}
                <div class="form-group">
                    {{ form.first_name.errors }}
                    <label for="{{ form.first_name.id_for_label }}">First Name</label>
                    {{ form.first_name }}
                </div>
                <div class="form-group">
                    {{ form.last_name.errors }}
                    <label for="{{ form.last_name.id_for_label }}">Last Name</label>
                    {{ form.last_name }}
                </div>
                <div class="form-group">
                    {{ form.street.errors }}
                    <label for="{{ form.street.id_for_label }}">Street</label>
                    {{ form.street }}
                </div>
                <div class="form-group">
                    {{ form.city.errors }}
                    <label for="{{ form.city.id_for_label }}">City</label>
                    {{ form.city }}
                </div>
                <div class="form-group">
                    {{ form.state.errors }}
                    <label for="{{ form.state.id_for_label }}">State</label>
                    {{ form.state }}
                </div>
                <div class="form-group">
                    {{ form.zipp.errors }}
                    <label for="{{ form.zipp.id_for_label }}">Zip</label>
                    {{ form.zipp }}
                </div>
                <div class="form-group">
                    {{ form.display_name.errors }}
                    <label for="{{ form.display_name.id_for_label }}">Display Name</label>
                    {{ form.display_name }}
                </div>
                <div class="form-group">
                    {{ form.avatar.errors }}
                    <label for="{{ form.avatar.id_for_label }}">Avatar</label>
                    {{ form.avatar }}
                </div>
                <div class="form-group">
                    {{ form.email.errors }}
                    <label for="{{ form.email.id_for_label }}">Email</label>
                    {{ form.email }}
                </div>
                {{ signup.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sellers/templates/sellers/new2.html
{% extends "layout.html" %}


{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-danger alert-dismissible fade show" role="alert"{% endif %}>{{ message }}>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
    </li>
    
    {% endfor %}
</ul>
{% endif %}



<div class="form-container col-6 offset-3">
    <div class="row">
        <h1>Become a Provider</h1>
    </div>
    <div class="row">
        <div class="form">
            <form  method="post" action="" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-group">
                    {{ merch.phone.errors }}
                    <label for="{{ merch.phone.id_for_label }}">Phone Number</label>
                    {{ merch.phone }}
                </div>
                <div class="form-group">
                    {{ merch.dob.errors }}
                    <label for="{{ merch.dob.id_for_label }}">Date of Birth</label>
                    {{ merch.dob }}
                </div>
                <div class="form-group">
                    {{ merch.ssn.errors }}
                    <label for="{{ merch.ssn.id_for_label }}">Last Four of SSN</label>
                    {{ merch.ssn }}
                </div>
                <div class="form-group">
                    {{ merch.legal.errors }}
                    <label for="{{ merch.legal.id_for_label }}">Legal Name</label>
                    {{ merch.legal }}
                </div>
                <div class="form-group">
                    {{ merch.dba.errors }}
                    <label for="{{ merch.dba.id_for_label }}">DBA</label>
                    {{ merch.dba }}
                </div>
                <div class="form-group">
                    {{ merch.tax.errors }}
                    <label for="{{ merch.tax.id_for_label }}">Tax</label>
                    {{ merch.tax }}
                </div>
                <div class="form-group">
                    {{ merch.biz_street.errors }}
                    <label for="{{ merch.biz_street.id_for_label }}">Street</label>
                    {{ merch.biz_street }}
                </div>
                <div class="form-group">
                    {{ merch.biz_city.errors }}
                    <label for="{{ merch.biz_city.id_for_label }}">City</label>
                    {{ merch.biz_city }}
                </div>
                <div class="form-group">
                    {{ merch.biz_state.errors }}
                    <label for="{{ merch.biz_state.id_for_label }}">State</label>
                    {{ merch.biz_state }}
                </div>
                <div class="form-group">
                    {{ merch.biz_zipp.errors }}
                    <label for="{{ merch.biz_zipp.id_for_label }}">Zip</label>
                    {{ merch.biz_zipp }}
                </div>
                <div class="form-group">
                    {{ merch.funding_name.errors }}
                    <label for="{{ merch.funding_name.id_for_label }}">Bank Name</label>
                    {{ merch.funding_name }}
                </div>
                <div class="form-group">
                    {{ merch.acc_num.errors }}
                    <label for="{{ merch.acc_num.id_for_label }}">Bank Account Number</label>
                    {{ merch.acc_num }}
                </div>
                <div class="form-group">
                    {{ merch.routing.errors }}
                    <label for="{{ merch.routing.id_for_label }}">Routing Number</label>
                    {{ merch.routing }}
                </div>
                <div class="form-group">
                    {{ merch.tos.errors }}
                    <label for="{{ merch.tos.id_for_label }}">Terms of Service</label>
                    {{ merch.tos }}
                </div>


                {{ signup.as_p }}
                <input type="submit" value="Submit" class="btn btn-primary"/>
            </form>
        </div>
    </div>
</div>
{% endblock %}

sellers/templates/sellers/profile.html
{% extends "layout.html" %}
{% load static  %}

{% block content %}

<table class="table table-hover">
    <thead class="thead-light">
        <tr>
            <th scope="col">Service</th>
            <th scope="col">Buyer</th>
            <th scope="col">Date Bought</th>
        </tr>
    </thead>
    <tbody>
        {% for bought in boughts %}
        <tr>
            
            <td>{{bought.item.name}}</td>
            <td>{{ bought.buyer.first_name }}</td>
            <td>{{ bought.created }}</td>
            <td><a href="{% url 'sellers:redeem' pk=bought.id %}">Reedem</a></td>
            
            
        </tr>
        {% endfor %}
    </tbody>
</table>

{% endblock %}

sellers/templates/sellers/redeem.html
<h1>Redeem Seller</h1>
<h1>{{ bought.item.name }}</h1>
<h1>{{ code }}</h1>