g2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r"^accounts/", include("accounts.urls", namespace='accounts')),
    url(r"^prof/", include("prof.urls", namespace='prof')),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^sellers/', include('sellers.urls', namespace='sellers')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

prof/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.bought_listings, name='bought_listings'),
    url(r'^redeem_detail/(?P<pk>\d+)', views.redeem_detail, name='redeem_detail'),
    url(r'redeem/(?P<pk>\d+)', views.redeem, name='redeem'),
    
]

prof/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from listings.models import Bought

class Code(models.Model):
    bought = models.ForeignKey(Bought, blank=False, null=False)
    code = models.CharField(max_length=10)
    created = models.DateTimeField(default=timezone.now)
    expire = models.DateTimeField()

prof/forms.py
from django import forms
from django.forms import ModelForm, TextInput
from . import models
from django.apps import apps
from listings.models import Bought




class RedeemForm(forms.ModelForm):
    class Meta:
        model = Bought
        fields = {
            'redeemed',
        }

        widgets = {
            'redeemed': TextInput(attrs={'cols': 80, 'rows': 20}),
        }

prof/views.py
from django.shortcuts import get_object_or_404, render
from listings.models import Listing, Bought
from .models import Code
from django.http import HttpResponseRedirect, HttpResponse
from . import forms
from . import models

# Create your views here.
def bought_listings(request):
    uid = request.user.id
    boughts = Bought.objects.filter(buyer=request.user.id)
    
    return render(request, 'prof/bought_listings.html', {'boughts': boughts})


def redeem_detail(request, pk):
    bought = get_object_or_404(Bought, pk=pk)
    return render(request, 'prof/redeem_detail.html', {'bought': bought})

def redeem(request, pk):
    cd = get_object_or_404(Code, bought=pk)
    bought = get_object_or_404(Bought, pk=pk)
    #expire = now + datetime.timedelta(minutes = 10)

    form = forms.RedeemForm()
    form = forms.RedeemForm(request.POST)
    redeem = form['redeemed']
    r = form.save(commit=False)
    if redeem.value() == cd.code:
        bought.redeemed = True
        bought.save()
        return HttpResponseRedirect('/listings/home/')
    else:
        print(bought.id)
        print(cd.code)
        print("Not Correct code")
 
       

    return render(request, 'prof/redeem.html', {'form':form})

prof/templates/prof/bought_listings.html
{% extends "layout.html" %}
{% load static  %}

{% block content %}
    <div class="row">
        <div>
            <h1>Purchased Listings</h1>


        </div>
    </div>
    <div>
        {% if boughts %}
            {%  for bought in boughts %}
                {% if forloop.first %}<div class="row">{% endif %}
                    <div class="col-sm-4">
                        <a href="{% url 'prof:redeem_detail' pk=bought.pk %}">
                                <div class="card" style="width: 20rem;">
                                <img class="card-img-top" src="{{ MEDIA_URL }}{{bought.item.document}}" alt="Card image cap">
                            </a>
                                <div class="card-body">
                                    <a href="{% url 'prof:redeem_detail' pk=bought.pk %}">
                                        <h4 class="card-title">{{ bought.item.name }} - {{ bought.id }}</h4>
                                        <p class="card-text">{{bought.item.desc}}</p>
                                    </a>
                                </div>
                            
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                    {% if forloop.last %}</div>{% endif %}

            {% endfor %}
        {% else %}
            <h1>You Do Not Have Any Listings</h1>
        {% endif %}
    </div>
{% endblock %}

prof/templates/prof/redeem.html
{% extends "layout.html" %}
<head>
    <meta charset="utf-8">
    <script src="https://js.braintreegateway.com/web/dropin/1.8.0/js/dropin.min.js"></script>
</head>



{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-success alert-dismissible fade show" role="alert"{% endif %}>{{ message }}>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
    </li>
    
    {% endfor %}
</ul>
{% endif %}
<h1>{{ listing.name }}</h1>
<div class="row">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}

prof/templates/prof/redeem_detail.html
{% extends "layout.html" %}

{% block content %}
<h1>This is redeem</h1>
<h1>{{ bought.item.name }}</h1>
<h1>{{ bought.item.created }}</h1>
<a href="{% url 'prof:redeem' pk=bought.pk %}">Redeem</a>

{% endblock %}