g2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r"^accounts/", include("accounts.urls", namespace='accounts')),
    url(r"^prof/", include("prof.urls", namespace='prof')),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^sellers/', include('sellers.urls', namespace='sellers')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'home/$', views.Home, name='home'),
    url(r'^checkouts/(?P<pk>\d+)/', views.new_checkout, name='new_checkout'),
    url(r'new/$', views.New, name='new'),
    url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.Edit, name='edit'),
    url(r'my/$', views.MyListings, name='my_listings'),
    url(r'^client_token', views.client_token, name='client_token'),
    url(r'^checkouts/create/(?P<pk>\d+)', views.create_checkout, name='create_checkout'),
    url(r'^checkouts/(?P<transaction_id>\w+)/(?P<pk>\d+)', views.show_checkout, name='show_checkout'),
]

listings/models.py
from django.db import models
from django.forms import ModelForm
from django.contrib.auth import get_user_model
from django.contrib.auth.models import User
from django.conf import settings
from django.utils import timezone
from sellers.models import Seller

# Create your models here.
# Create the form class.
class Listing(models.Model):
    name = models.CharField(max_length=50)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    user = models.ForeignKey(to=settings.AUTH_USER_MODEL, blank=True, null=True)
    document = models.FileField(upload_to='documents/', null=True)
    created = models.DateTimeField(default=timezone.now)
    is_active = models.BooleanField(default=True)
    status = models.CharField(default="",null=True, blank=True, max_length=10)

    desc = models.TextField()
    
    HOUR = 'hr'
    SESSION = 'ss'

    UNIT_CHOICES = (
        (HOUR, 'Hour'),
        (SESSION, 'Session',)
    )

    unit = models.CharField(
        max_length = 2,
        choices = UNIT_CHOICES,
        default = HOUR,
    )

    def __str__(self):              # __unicode__ on Python 2
        return self.name


class Bought(models.Model):
    buyer = models.ForeignKey(to=settings.AUTH_USER_MODEL, blank=True, null=True, related_name='buyers')
    seller = models.ForeignKey(Seller,null=True, blank=True)
    item = models.ForeignKey(Listing, blank=True, null=True, related_name='items')
    trans_id = models.CharField(default="",null=True, blank=True, max_length=8)
    created = models.DateTimeField(default=timezone.now)
    redeemed = models.BooleanField(default=False)

listings/forms.py
from django import forms
from . import models
class ListingForm(forms.ModelForm):
    class Meta:
        model = models.Listing
        fields = [
            'name',
            'price',
             'desc',
             'unit',
             'document',
             'is_active',
        ]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Name'})
        self.fields["price"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Price'})
        self.fields["desc"].widget.attrs.update({'class': 'form-control','placeholder': 'Description'})
        self.fields["unit"].widget.attrs.update({'class': 'form-control', 'placeholder': 'Per Hour or Session'})
        self.fields["document"].widget.attrs.update({'class': 'form-control'})
        self.fields["is_active"].widget.attrs.update({'class': 'form-control form-check-input'})
        

class BoughtForm(forms.ModelForm):
    class Meta:
        model = models.Bought
        fields = {
            
        }
        
class DeleteForm(forms.ModelForm):
    class Meta:
        model = models.Listing
        fields = {
            
        }

class StatusForm(forms.ModelForm):
    class Meta:
        model = models.Listing
        fields = {
            
        }

listings/views.py
from __future__ import unicode_literals

from django.core.urlresolvers import reverse
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from . import forms
from . import models
from listings.models import Listing
from sellers.models import Seller
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.views.decorators.csrf import csrf_exempt

import braintree
# Create your views here.

def Home(request):
    listings = Listing.objects.filter(is_active=True)
    return render(request, 'listings/listing_home.html', {'listings':listings})

@login_required
def New(request):
    form = forms.ListingForm()
    # if this is a POST request we need to process the form data
    if request.user.is_seller == True:
        if request.method == 'POST':
            # create a form instance and populate it with data from the request:
            form = forms.ListingForm(request.POST, request.FILES)
            # check whether it's valid:
            if form.is_valid():
                # process the data in form.cleaned_data as required
                listing = form.save(commit=False)
                listing.user = request.user
                listing.is_active = True
                listing.save()
                messages.add_message(request, messages.SUCCESS, "Listing added")
                # redirect to a new URL:
                return HttpResponseRedirect('/listings/home/')

        return render(request, 'listings/new.html', {'form': form})
    else:
        messages.add_message(request, messages.ERROR, "You have to sign up for a seller account before you can post a listing.")
        return HttpResponseRedirect('/sellers/new/')

def detail(request, pk):
    listing = get_object_or_404(models.Listing, pk=pk) 
    form = forms.DeleteForm(instance=listing)
    if request.method == 'POST':
        form = forms.DeleteForm(instance=listing, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save(commit=False)
            listing.is_active = False
            form.save()
            messages.success(request, "Listing Deleted")
            return HttpResponseRedirect('/sellers/home/')
    return render(request, 'listings/detail.html', {'listing': listing, 'form': form})



@login_required    
def Edit(request, pk):
    listing = get_object_or_404(models.Listing, pk=pk) 
    form = forms.ListingForm(instance=listing)
    
    if request.method == 'POST':
        form = forms.ListingForm(instance=listing, data=request.POST, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, "Updated {}".format(form.cleaned_data['name']))
            return HttpResponseRedirect('/sellers/home/')
    return render(request, 'listings/edit.html', {'form': form})

def MyListings(request):
    uid = request.user.id
    listings = Listing.objects.filter(user_id=uid, is_active=True)
    return render(request, 'listings/my_listings.html', {'listings': listings})


def client_token(request):
  return braintree.ClientToken.generate()
@csrf_exempt
def new_checkout(request, pk):
    client_token = braintree.ClientToken.generate()
    listing = get_object_or_404(models.Listing, pk=pk)
    request.session["user"] = request.user.id
    return render(request,'listings/new_checkout.html', {'client_token':client_token, 'listing':listing})

def show_checkout(request,transaction_id, pk):
    transaction = braintree.Transaction.find(transaction_id)
    print(transaction)
    result = {}
    TRANSACTION_SUCCESS_STATUSES = [
    braintree.Transaction.Status.Authorized,
    braintree.Transaction.Status.Authorizing,
    braintree.Transaction.Status.Settled,
    braintree.Transaction.Status.SettlementConfirmed,
    braintree.Transaction.Status.SettlementPending,
    braintree.Transaction.Status.Settling,
    braintree.Transaction.Status.SubmittedForSettlement
]
    if transaction.status in TRANSACTION_SUCCESS_STATUSES:
        print(transaction.status)
        listing = get_object_or_404(models.Listing, pk=pk)
        form = forms.BoughtForm(instance=listing)
        # if this is a POST request we need to process the form data
            # create a form instance and populate it with data from the request:
        form = forms.BoughtForm(request.POST)
            # check whether it's valid:
            #if form.is_valid():
                # process the data in form.cleaned_data as required
        listing = get_object_or_404(models.Listing, pk=pk)
        bought = form.save(commit=False)
        bought.buyer = request.user
        bought.seller = get_object_or_404(Seller, pk=listing.user_id)
        bought.item = Listing.objects.get(id = listing.id)
        bought.trans_id = transaction_id
        bought.save()
    if transaction.status in TRANSACTION_SUCCESS_STATUSES:
        print(transaction.status)
        result = {
            'header': 'Sweet Success!',
            'icon': 'success',
            'message': 'Your test transaction has been successfully processed. See the Braintree API response and try again.'
        }
    else:
        result = {
            'header': 'Transaction Failed',
            'icon': 'fail',
            'message': 'Your test transaction has a status of ' + transaction.status + '. See the Braintree API response and try again.'
        }

    return render(request,'listings/show_checkout.html', {'transaction':transaction, 'result':result, 'form':form})

def create_checkout(request, pk):
    listing = get_object_or_404(models.Listing, pk=pk)
    print("Create")
    a = float(request.POST['amount'])
    escrow = round(a * .15, 2)
    escrow_amount = str(escrow)
    result = braintree.Transaction.sale({
        'amount': request.POST['amount'],
        "merchant_account_id": "janesladders_instant_0cg6sqt5",
        'payment_method_nonce': request.POST['payment_method_nonce'],
        'options': {
            "submit_for_settlement": True,
            "hold_in_escrow": True,
        },
        "service_fee_amount": escrow_amount,
    })

    if result.is_success or result.transaction:
        print("yes")
        return HttpResponseRedirect('/listings/checkouts/{0}/{1}'.format(result.transaction.id, pk))
    else:
        
        for x in result.errors.deep_errors: print('Error: %s: %s' % (x.code, x.message))
        return HttpResponseRedirect('listings/checkouts/%i' % listing.id)

if __name__ == '__main__':
    app.run(host='0.0.0.0', port=PORT, debug=True)

listings/templates/listings/bought.html
{% extends "layout.html" %}
<head>
    <meta charset="utf-8">
    <script src="https://js.braintreegateway.com/web/dropin/1.8.0/js/dropin.min.js"></script>
</head>



{% block content %}
{% if messages %}
<ul class="messages">
    {% for message in messages %}
    <li{% if message.tags %} class="alert alert-success alert-dismissible fade show" role="alert"{% endif %}>{{ message }}>
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"> <span aria-hidden="true">&times;</span></button>
    </li>
    
    {% endfor %}
</ul>
{% endif %}
<h1>{{ listing.name }}</h1>
<div class="row">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="seller" value="{{ listing.user_id }}" />
        <input type="submit" value="Submit" />
    </form>
</div>

{% endblock %}

listings/templates/listings/delete.html
{% extends "layout.html" %}


{% block content %}
<div class="row">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}

        <input type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

listings/templates/listings/detail.html
{% extends "layout.html" %}

{% block content %}

<h1>{{ listing.name }}</h1>
<h1>{{ listing.created }}</h1>

<a href="{% url 'listings:new_checkout' pk=listing.pk %}" class="btn btn-primary">Buy</a>
{% if listing.user_id == request.user.id %}
    <div class="row">
        <form  method="post" action="" enctype="multipart/form-data">
            {% csrf_token %}
            {{ form.non_field_errors }}

            <input class="btn btn-danger" type="submit" value="Delete" />
        </form>
    </div>
{% endif %}

{% endblock %}

listings/templates/listings/edit.html
{% extends "layout.html" %}


{% block content %}
<div class="row">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.name.errors }}
            <label for="{{ form.name.id_for_label }}">Listing Name</label>
            {{ form.name }}
        </div>
        <div class="form-group">
            {{ form.price.errors }}
            <label for="{{ form.price.id_for_label }}">Price</label>
            {{ form.price }}
        </div>
        <div class="form-group">
            {{ form.desc.errors }}
            <label for="{{ form.desc.id_for_label }}">Description</label>
            {{ form.desc }}
        </div>
        <div class="form-group">
            {{ form.unit.errors }}
            <label for="{{ form.unit.id_for_label }}">Session Payment</label>
            {{ form.unit }}
        </div>
        <div class="form-group">
            {{ form.document.errors }}
            <label for="{{ form.document.id_for_label }}">Listing Image</label>
            {{ form.document }}
        </div>

        <input type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

listings/templates/listings/listing_home.html
{% extends "layout.html" %}
{% load static  %}

{% block content %}
    <div class="row">
        <div>
            <h1>Listings</h1>
            <h1>{{ num }}</h1>
            {% if user.sellers %}
            <h1>Hello</h1>
            {% endif %}

        </div>
        <div>
            {% if user.is_seller == True %}
                <a class='btn btn-primary' role="button" href="{% url 'listings:new' %}">New Listing</a>
            {% endif %}
        </div>
    </div>
    <div>
        {%  for listing in listings %}
            {% if forloop.first %}<div class="row">{% endif %}
                <div class="col-sm-4">
                        <a href="{% url 'listings:detail' pk=listing.pk %}">
                            <div class="card" style="width: 20rem;">
                            <img class="card-img-top" src="{{ MEDIA_URL }}/{{listing.document}}" alt="Card image cap">
                        </a>
                            <div class="card-body">
                                <a href="{% url 'listings:detail' pk=listing.pk %}">
                                    <h4 class="card-title">{{ listing.name }}</h4>
                                    <p class="card-text">{{listing.desc}}</p>
                                </a>
                                {% if listing.user_id == request.user.id %}
                                    <a class="btn btn-primary" href="{% url 'listings:edit' pk=listing.pk %}">Edit</a>
                                {% endif %}
                            </div>
                        
                    </div>
                </div>
                {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                {% if forloop.last %}</div>{% endif %}
        {% endfor %}
    
    </div>
{% endblock %}

listings/templates/listings/my_listings.html
{% extends "layout.html" %}
{% load static  %}

{% block content %}
    <div class="row">
        <div>
            <h1>My Listings</h1>


        </div>
        <div>
            {% if user.is_seller == True %}
                <a class='btn btn-primary' role="button" href="{% url 'listings:new' %}">New Listing</a>
            {% endif %}
        </div>
    </div>
    <div>
        {% if listings %}
            {%  for listing in listings %}
                {% if forloop.first %}<div class="row">{% endif %}
                    <div class="col-sm-4">
                            <a href="{% url 'listings:detail' pk=listing.pk %}">
                                <div class="card" style="width: 20rem;">
                                <img class="card-img-top" src="{{ MEDIA_URL }}/{{listing.document}}" alt="Card image cap">
                            </a>
                                <div class="card-body">
                                    <a href="{% url 'listings:detail' pk=listing.pk %}">
                                        <h4 class="card-title">{{ listing.name }}</h4>
                                        <p class="card-text">{{listing.desc}}</p>
                                    </a>
                                    {% if listing.user_id == request.user.id %}
                                        <a class="btn btn-primary" href="{% url 'listings:edit' pk=listing.pk %}" onclick='overlay()' >Edit</a>
                                    {% endif %}
                                </div>
                            
                        </div>
                    </div>
                    {% if forloop.counter|divisibleby:3 %}</div><div class="row">{% endif %}
                    {% if forloop.last %}</div>{% endif %}
            {% endfor %}
        {% else %}
            <h1>You Do Not Have Any Listings</h1>
        {% endif %}
    </div>
{% endblock %}

listings/templates/listings/new.html
{% extends "layout.html" %}


{% block content %}
<div class="row">
    <form  method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Submit" />
    </form>
</div>
{% endblock %}

listings/templates/listings/new_checkout.html
{% extends 'layout.html' %}
{% block content %}

<div class="wrapper">
  <div class="checkout container">

    <header>
      <h1>Hi, <br>Let's test a transaction</h1>
      <p>
        Make a test payment with Braintree using PayPal or a card
      </p>
    </header>

    <form id="payment-form" method="post" action="/listings/checkouts/create/{{listing.id}}">
      {% csrf_token %}
      <section>
        <label for="amount">
          <span class="input-label">Amount</span>
          <div class="input-wrapper amount-wrapper">
            <h6>{{ listing.price }}</h6>
            <input id="amount" name="amount" type="hidden" min="1" placeholder="Amount" value="{{ listing.price }}">
          </div>
        </label>

        <div class="bt-drop-in-wrapper">
          <div id="bt-dropin"></div>
        </div>
      </section>

      <input type="hidden" id="nonce" name="payment_method_nonce" />
      <button class="button" type="submit" id="submit-button"><span>Test Transaction</span></button>
    </form>

  </div>
</div>

<script src="https://js.braintreegateway.com/web/dropin/1.8.1/js/dropin.min.js"></script>
<script>
  var form = document.querySelector('#payment-form');
  var client_token = '{{ client_token }}';
  braintree.dropin.create({
    authorization: client_token,
    container: '#bt-dropin',
    card: {
      cardholderName: true
    },
    paypal: {
      flow: 'vault'
    }
 
  }, function (createErr, instance) {
    form.addEventListener('submit', function (event) {
      event.preventDefault();
      instance.requestPaymentMethod(function (err, payload) {
        if (err) {
          console.log('Error', err);
          return;
        }
        // Add the nonce to the form and submit
        document.querySelector('#nonce').value = payload.nonce;
        form.submit();
      });
    });
  });
  var checkout = new Demo({
    formID: 'payment-form'
  });
</script>
{% endblock %}

listings/templates/listings/show_checkout.html
{% extends 'layout.html' %}
{% block content %}
<div class="wrapper">
  <div class="response container">
    <div class="content">
      <div class="icon">
        
      </div>

      <h1>{{ result.header }}</h1>
      <section>
        <p>{{ result.message }}</p>
      </section>

      <section>
        <a class="button primary back" href="/checkouts/new">
          <span>Test Another Transaction</span>
        </a>
      </section>
    </div>
  </div>
</div>
<aside class="drawer dark">
  <header>
    <div class="content compact">
      <a href="https://developers.braintreepayments.com" class="braintree" target="_blank">Braintree</a>
      <h3>API Response</h3>
    </div>
  </header>
  <div class="row">
    <form  name="bought" id-"bought" method="post" action="" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form.as_p }}
        <input type="hidden" name="seller" value="{{ listing.user_id }}" />
        
    </form>
</div>

  <article class="content compact">
  <section>
    <h5>Transaction</h5>
      <table cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td>id</td>
            <td>{{ transaction.id }}</td>
          </tr>
          <tr>
            <td>type</td>
            <td>{{ transaction.type }}</td>
          </tr>
          <tr>
            <td>amount</td>
            <td>{{ transaction.amount }}</td>
          </tr>
          <tr>
            <td>status</td>
            <td>{{ transaction.status }}</td>
          </tr>
          <tr>
            <td>created_at</td>
            <td>{{ transaction.created_at }}</td>
          </tr>
          <tr>
            <td>updated_at</td>
            <td>{{ transaction.updated_at }}</td>
          </tr>
        </tbody>
      </table>
    </section>

    <section>
      <h5>Payment</h5>

      <table cellpadding="0" cellspacing="0">
        <tbody>
          <tr>
            <td>token</td>
            <td>{{ transaction.credit_card_details.token }}</td>
          </tr>
          <tr>
            <td>bin</td>
            <td>{{ transaction.credit_card_details.bin }}</td>
          </tr>
          <tr>
            <td>last_4</td>
            <td>{{ transaction.credit_card_details.last_4 }}</td>
          </tr>
          <tr>
            <td>card_type</td>
            <td>{{ transaction.credit_card_details.card_type }}</td>
          </tr>
          <tr>
            <td>expiration_date</td>
            <td>{{ transaction.credit_card_details.expiration_date }}</td>
          </tr>
          <tr>
            <td>cardholder_name</td>
            <td>{{ transaction.credit_card_details.cardholder_name }}</td>
          </tr>
          <tr>
            <td>customer_location</td>
            <td>{{ transaction.credit_card_details.customer_location }}</td>
          </tr>
        </tbody>
      </table>
    </section>

    {% if transaction.customer_details.id %}
      <section>
        <h5>Customer Details</h5>
        <table cellpadding="0" cellspacing="0">
          <tbody>
            <tr>
              <td>id</td>
              <td>{{ transaction.customer_details.id }}</td>
            </tr>
            <tr>
              <td>first_name</td>
              <td>{{ transaction.customer_details.first_name }}</td>
            </tr>
            <tr>
              <td>last_name</td>
              <td>{{ transaction.customer_details.last_name }}</td>
            </tr>
            <tr>
              <td>email</td>
              <td>{{ transaction.customer_details.email }}</td>
            </tr>
            <tr>
              <td>company</td>
              <td>{{ transaction.customer_details.company }}</td>
            </tr>
            <tr>
              <td>website</td>
              <td>{{ transaction.customer_details.website }}</td>
            </tr>
            <tr>
              <td>phone</td>
              <td>{{ transaction.customer_details.phone }}</td>
            </tr>
            <tr>
              <td>fax</td>
              <td>{{ transaction.customer_details.fax }}</td>
            </tr>
          </tbody>
        </table>
      </section>
    {% endif %}

    <section>
      <p class="center small">Integrate with the Braintree SDK for a secure and seamless checkout</p>
    </section>

    <section>
      <a class="button secondary full" href="https://developers.braintreepayments.com/guides/drop-in" target="_blank">
        <span>See the Docs</span>
      </a>
    </section>
  </article>
</aside>
{% endblock %}