accounts/urls.py
from django.conf.urls import url
from django.contrib.auth import views as auth_views

from . import views

urlpatterns = [
    # url(r"login/$", views.LoginView.as_view(), name="login"),
    url(r"logout/$", views.LogoutView.as_view(), name="logout"),
    url(r"signup/$", views.SignUp.as_view(), name="signup"),
    url(r'edit/$', views.Edit, name='edit'),
    url(r'^login/$', views.login, name='login'),
    url(r'^profile/$', views.Profile, name='profile'),
]

g2/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.conf import settings
from django.conf.urls.static import static
from graphene_django.views import GraphQLView

from . import views

urlpatterns = [
    url(r"^$", views.Home.as_view(), name="home"),
    url(r"^admin/", admin.site.urls),
    url(r'^listings/', include('listings.urls', namespace='listings')),
    url(r"^accounts/", include("accounts.urls", namespace='accounts')),
    url(r"^prof/", include("prof.urls", namespace='prof')),
    url(r"^accounts/", include("django.contrib.auth.urls")),
    url(r'^sellers/', include('sellers.urls', namespace='sellers')),
    url(r'^graphql', GraphQLView.as_view(graphiql=True)),
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

listings/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'home/$', views.Home, name='home'),
    url(r'^checkouts/(?P<pk>\d+)/', views.new_checkout, name='new_checkout'),
    url(r'new/$', views.New, name='new'),
    url(r'(?P<pk>\d+)/$', views.detail, name='detail'),
    url(r'(?P<pk>\d+)/edit/$', views.Edit, name='edit'),
    url(r'my/$', views.MyListings, name='my_listings'),
    url(r'^client_token', views.client_token, name='client_token'),
    url(r'^checkouts/create/(?P<pk>\d+)', views.create_checkout, name='create_checkout'),
    url(r'^checkouts/(?P<transaction_id>\w+)/(?P<pk>\d+)', views.show_checkout, name='show_checkout'),
]

prof/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'^$', views.bought_listings, name='bought_listings'),
    url(r'^redeem_detail/(?P<pk>\d+)', views.redeem_detail, name='redeem_detail'),
    url(r'redeem/(?P<pk>\d+)', views.redeem, name='redeem'),
    
]

sellers/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

urlpatterns = [
    url(r'home/$', views.Home, name='home'),
    url(r'new/$', views.New, name='new'),
    url(r'new2/$', views.TwoNew, name='two_new'),
    url(r'^profile/$', views.Profile, name='profile'),
    url(r'redeem/(?P<pk>\d+)/$', views.redeem, name='redeem'),

]

templates/index.html
{% extends "layout.html" %}
{% load static  %}

{% block content %}
	

	<h1>Hello</h1>


			
{% endblock %}

templates/layout.html
{% load static  %}
<!doctype html>
<html lang="en">
    <head>
        <title>Gidget</title>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/css/bootstrap.min.css" integrity="sha384-PsH8R72JQ3SOdhVi3uxftmaW6Vc51MKb0q5P2rRUpPvrszuE4W1povHYgTpBfshb" crossorigin="anonymous">        
        <link rel="stylesheet"  type="text/css" href="{% static 'css/base.css' %}" />
        <link type="text/javascript" href="{% static 'js/app.js' %}"/>
       
    </head>
    <body>
        <nav class="navbar navbar-expand-lg navbar-light bg-light">
                <a class="navbar-brand" href="#">Navbar</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'listings:home' %}">Listings</a>
                    </li>
                    {% if user.is_authenticated %}
                    {% if user.is_seller == True %}
                    <li class="nav-item dropdown">
                        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Sellers
                        </a>
                        <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        <a class="dropdown-item" href="{% url 'sellers:profile' %}">Profile</a>
                        <a class="dropdown-item" href="{% url 'listings:my_listings' %}">My Listings</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="#">Something else here</a>
                        </div>
                    </li>
                    {% else %}
                    <a class="nav-link" href="{% url 'sellers:new' %}">Become A Provider</a>
                    {% endif %}
                    {% endif %} 
                    <li class="nav-item">
                        {% if user.is_authenticated %}
                            <a class="nav-link mr-sm-2" href="{% url 'logout'%}?next={{request.path}}">Logout</a>
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Hello {{ user.first_name }}
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="dropdown-item" href="{% url 'accounts:profile' %}">Profile</a>
                                <a class="dropdown-item" href="{% url 'prof:bought_listings' %}">Bought Listings</a>
                                <div class="dropdown-divider"></div>
                                <a class="dropdown-item" href="#">Something else here</a>
                                </div>
                            </li>   
                        {% else %}
                        
                        <li class="nav-item"><a class="nav-link" href="{% url 'login'%}?next={{request.path}}">Login</a></li> 
                        <li class="nav-item"><a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a></li>
                        
                        {% endif %} 
                    </li>
                    </ul>
                    <form class="form-inline my-2 my-lg-0">
                    <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
                    </form>
                </div>
            </nav>
            <div class="container">
                {% block content %}{% endblock %}
            </div>


            
            <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
            <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
            <script src="https://static.opentok.com/v2/js/opentok.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/underscore.js/1.8.3/underscore-min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.17.1/moment.min.js"></script>
            <script src="https://cdnjs.cloudflare.com/ajax/libs/livestamp/1.1.2/livestamp.min.js"></script>
            <script src="https://js.braintreegateway.com/web/dropin/1.8.1/js/dropin.min.js"></script>
            <script src="{% static 'js/app.js' %}"></script>
            {% block javascript %}{% endblock %}
    </body>
</html>